name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: "Test building package"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/stertooy/gda-image:tex-full

    steps:
      - uses: actions/checkout@v4
        with:
          repository: gap-packages/example
      - uses: actions/checkout@v4
        with:
          path: ./this-action/
      - uses: stertooy/gda-build-pkg@v1
      - uses: ./this-action/
      - uses: actions/upload-artifact@v4
        with:
          path: ./doc/manual.pdf
          if-no-files-found: error
